### ISSUE TITLE
Failed to install on ubuntu 18.04 

### ISSUE THREAD

**Issue by Jolles-workm8** [Czaki/imagecodecs#6]
```
from /usr/include/python3.6m/numpy/arrayobject.h:4,
                   from imagecodecs/_shared.c:599:
  /usr/include/python3.6m/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^~~~~~~
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/imagecodecs/_shared.o -lm -o build/lib.linux-x86_64-3.6/imagecodecs/_shared.cpython-36m-x86_64-linux-gnu.so
  skipping 'imagecodecs/_snappy.c' Cython extension (up-to-date)
  building 'imagecodecs._snappy' extension
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Iimagecodecs -I/usr/include/python3.6m -I/home/jolles/.local/lib/python3.6/site-packages/numpy/core/include -c imagecodecs/_snappy.c -o build/temp.linux-x86_64-3.6/imagecodecs/_snappy.o
  In file included from /usr/include/python3.6m/numpy/ndarraytypes.h:1809:0,
                   from /usr/include/python3.6m/numpy/ndarrayobject.h:18,
                   from /usr/include/python3.6m/numpy/arrayobject.h:4,
                   from imagecodecs/_snappy.c:598:
  /usr/include/python3.6m/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^~~~~~~
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/imagecodecs/_snappy.o -lm -lsnappy -o build/lib.linux-x86_64-3.6/imagecodecs/_snappy.cpython-36m-x86_64-linux-gnu.so
  skipping 'imagecodecs/_tiff.c' Cython extension (up-to-date)
  building 'imagecodecs._tiff' extension
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Iimagecodecs -I/usr/include/python3.6m -I/home/jolles/.local/lib/python3.6/site-packages/numpy/core/include -c imagecodecs/_tiff.c -o build/temp.linux-x86_64-3.6/imagecodecs/_tiff.o
  In file included from /usr/include/python3.6m/numpy/ndarraytypes.h:1809:0,
                   from /usr/include/python3.6m/numpy/ndarrayobject.h:18,
                   from /usr/include/python3.6m/numpy/arrayobject.h:4,
                   from imagecodecs/_tiff.c:598:
  /usr/include/python3.6m/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^~~~~~~
  imagecodecs/_tiff.c: In function ‘__pyx_pymod_exec__tiff’:
  imagecodecs/_tiff.c:29393:36: error: ‘COMPRESSION_ZSTD’ undeclared (first use in this function); did you mean ‘COMPRESSION_LZW’?
     __pyx_t_5 = __Pyx_PyInt_From_int(COMPRESSION_ZSTD); if (unlikely(!__pyx_t_5)) __PYX_ERR(0, 84, __pyx_L1_error)
                                      ^~~~~~~~~~~~~~~~
                                      COMPRESSION_LZW
  imagecodecs/_tiff.c:29393:36: note: each undeclared identifier is reported only once for each function it appears in
  imagecodecs/_tiff.c:29405:36: error: ‘COMPRESSION_WEBP’ undeclared (first use in this function); did you mean ‘COMPRESSION_NEXT’?
     __pyx_t_5 = __Pyx_PyInt_From_int(COMPRESSION_WEBP); if (unlikely(!__pyx_t_5)) __PYX_ERR(0, 85, __pyx_L1_error)
                                      ^~~~~~~~~~~~~~~~
                                      COMPRESSION_NEXT
  At top level:
  imagecodecs/_tiff.c:10261:47: warning: ‘__pyx_f_11imagecodecs_5_tiff_memtif_new’ defined but not used [-Wunused-function]
   static __pyx_t_11imagecodecs_5_tiff_memtif_t *__pyx_f_11imagecodecs_5_tiff_memtif_new(toff_t __pyx_v_size, toff_t __pyx_v_inc) {
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for imagecodecs
  Running setup.py clean for imagecodecs
Failed to build imagecodecs
Installing collected packages: numpy, scanimage-tiff-reader, imagecodecs, tifffile, six, scipy, h5py, keras-applications, pyyaml, keras-preprocessing, keras, python-dateutil, setuptools, kiwisolver, cycler, pyparsing, matplotlib, Pillow, decorator, networkx, pytz, pandas, seaborn, alt-model-checkpoint
  Running setup.py install for imagecodecs ..
```

**Comment by Czaki** [comment]
You build against system library or manually compiled one? Because of changes introduced by package author (This repo is for creating wheels) I drop testing build on ubuntu 18.04 basic on libraries from repository because of too old version .

Your message suggest that you do not have installed libtiff (because undeclared symbols comes form this library). This library is added to `imagecodecs` dependency after  2019.12.31 release

**Comment by eduardogspereira** [comment]
Hi @Czaki ^^

I'm having the same issue here on ubuntu 18.04.
I installed with the packages listed at https://pypi.org/project/imagecodecs/.
I also installed `libtiff-dev`, do you think that I may be missing another package?

**- os-release**
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
```

**- installed packages**

```
apt-get install -y \
  build-essential python3-dev cython3 python3-setuptools python3-pip \
  python3-wheel python3-numpy python3-pytest python3-blosc python3-brotli \
  python3-snappy python3-lz4 libz-dev libblosc-dev liblzma-dev liblz4-dev \
  libzstd-dev libpng-dev libwebp-dev libbz2-dev libopenjp2-7-dev libjpeg-turbo8-dev \
  libjxr-dev liblcms2-dev libcharls-dev libaec-dev libbrotli-dev libsnappy-dev \
  libzopfli-dev libgif-dev libtiff-dev libtiff-opengl
```

**Comment by Czaki** [comment]
@eduardogspereira Did you need to compile it manually or you can use version from wheel? 

default version of pip in ubuntu 18.04 is 9. to install wheel with manylinux 2010 platform tag there is need to have pip in version at least 18. 

Maybe best solution is upgrade pip with `pip install -U pip` then you can easy install `imagecodecs`

**Comment by eduardogspereira** [comment]
Yep, upgrading the pip did the trick. Thanks @Czaki!!

**Comment by Czaki** [comment]
@Jolles-workm8 @eduardogspereira  
In ubuntu 18.04 libtiff is in the version 4.0.9. imagecodecs is developed base on version 4.1.0. 

In 4.0.9 COMPRESSION_ZSTD is not defined. So I suggest to install imagecodecs from wheel (which needs modern version of pip, 1t least 19.0) or manually compile libtiff in new version.

**Comment by mmartial** [comment]
> @Jolles-workm8 @eduardogspereira
> In ubuntu 18.04 libtiff is in the version 4.0.9. imagecodecs is developed base on version 4.1.0.
> 
> In 4.0.9 COMPRESSION_ZSTD is not defined. So I suggest to install imagecodecs from wheel (which needs modern version of pip, at least 19.0) or manually compile libtiff in new version.

There is no `arm64` wheel version, so this does affect builds on such systems (ex: Jetson Nano) with Ubuntu 18.04. I will try to see if a 20.04 based container works next.
